version: "3.8"

services:
  bioluminescence-api:
    build: .
    container_name: bioluminescence-ai
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database for storing validation data and model parameters
  postgres:
    image: postgres:13
    container_name: bioluminescence-db
    environment:
      POSTGRES_DB: bioluminescence
      POSTGRES_USER: luxbio
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Optional: Redis for caching and job queues
  redis:
    image: redis:6-alpine
    container_name: bioluminescence-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
