version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://83.229.67.244:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - bioluminescent-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://83.229.67.244:3000,https://83.229.67.244:3000
    networks:
      - bioluminescent-network

networks:
  bioluminescent-network:
    driver: bridge 